name: gh-cli

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/gh-cli.yml'
  workflow_dispatch: # manual trigger

jobs:
    gh-cli-job:
        runs-on: ubuntu-latest
        env:
            env: env-test
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        steps:
            - uses: actions/checkout@v4
            - run: env| grep GH_TOKEN
            # - run: gh auth login
            # - run: gh auth status
            - run: gh repo list
            - run: gh issue list
            - run: gh workflow list
            - run: gh api /repos/gprzemas/course-gh-actions/actions/workflows
            - run: gh api /repos/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/workflows
